### ISSUE TITLE
doesn't add <amp-analytics> tag in footer

### ISSUE THREAD

**Issue by emidiao** [rolandfarkasCOM/ampanalyticssupport#1]
shouldn't it be 'amp_post_template_footer' instead of 'wp_footer'?

**Comment by rolandfarkasCOM** [comment]
Hey @emidiao, 

It seems like `amp_post_template_footer` is for Reader mode while wp_footer works for both Standard and Transitional. 

I updated the next release and it is also available directly from [https://wordpress.org/plugins/amp-google-analytics-4-support/
](https://wordpress.org/plugins/amp-google-analytics-4-support/
)
Thank you for raising the issue 🙏
